version: "3"
services:
  postgres:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
volumes:
  postgres:
